"""auto-phonenumber

Revision ID: 9934cde5c9e7
Revises: e26bbdaaab11
Create Date: 2022-01-10 18:07:20.015714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9934cde5c9e7'
down_revision = 'e26bbdaaab11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
